### ISSUE TITLE
Horizon-ZEN production launch

### ISSUE THREAD

**Issue by alejandromumo** [zenodo/zenodo-rdm#1011]
TODO:  add leftover tasks

### Tasks
- [ ] Modify "browse" button link, it should point to "community browse" page
- [ ] collections: logos as community files instead of static
- [x] collections: compute number of records (CLI)
- [x] browse page: improve small screen / mobile rendering
- [ ] subcommunities page: show "New upload" button next to each listed community
