### ISSUE TITLE
migration: community inclusion requests

### ISSUE THREAD

**Issue by kpsherva** [zenodo/zenodo-rdm#194]
## Zenodo

IRs are represented as ([DB model](https://github.com/inveniosoftware/invenio-communities/blob/v1.0.0a29/invenio_communities/models.py#L40)):
- community id
- record id
- user id
- expiration date 

The last two are nullable.

Creation, acceptance and removal happens directly against the model class from the Community/Deposit API
- [create](https://github.com/zenodo/zenodo/blob/master/zenodo/modules/deposit/api.py#L156)
- [accept](https://github.com/zenodo/zenodo/blob/master/zenodo/modules/communities/api.py#L150)
- [reject](https://github.com/zenodo/zenodo/blob/master/zenodo/modules/communities/api.py#L177)

## RDM

IRs are defined as a [Mixin](https://github.com/inveniosoftware/invenio-communities/blob/master/invenio_communities/records/records/models.py#L19) with 3 attributes, inherited in the [RDM Parent Community](https://github.com/inveniosoftware/invenio-rdm-records/blob/master/invenio_rdm_records/records/models.py#L35)
- request id
- community id
- record id

## Tasks

- [x] What to do with the global `zenodo` community?
- [ ] What to do with the user reference, does it make sense in RDM?
- [x] Obtain dump from Zenodo/Sandbox. Only one table is involved [`communities_community_record`](https://github.com/inveniosoftware/invenio-communities/blob/v1.0.0a29/invenio_communities/models.py#L40).
- [ ] The ETL classes should be minimal:
    - [ ] Two attributes, community and record id, destination table `rdm_parents_community`
    - [ ] The request id can be autogenerated, it needs to be cached (keep track) so it can be reference in the events
    - [ ] If the IR expired add Accepted Action otherwise a Expired Action. Zenodo does not keep track of Declined/Cancel actions. Create the Request Event of the corresponding type in [request_events](https://github.com/inveniosoftware/invenio-requests/blob/master/invenio_requests/records/models.py#L38). Can follow the types in the [submission review request](https://github.com/inveniosoftware/invenio-rdm-records/blob/master/invenio_rdm_records/requests/community_submission.py#L127).

**Extra**
- [ ] Should the M2M mixin be moved to rdm-records since it has context (requires) a record class to work? alternatively, move it to the `communities/records/` since it makes no sense to have an external `records/` in this module.
- [ ] Take into account https://github.com/inveniosoftware/invenio-requests/issues/303

**Comment by kpsherva** [comment]
~3 dev days estimated

**Comment by slint** [comment]
> * community id
> * record id
> * user id
> * expiration date
> 
> The last two are nullable.

On Zenodo currently `id_user` and `expires_at` are both always NULL.

> ## Tasks
> * [ ]  What to do with the global `zenodo` community?
This is a community used for featuring records on the frontpage. We shouldn't use it anymore and instead find a different, less intrusive, solution.

> * [ ]  What to do with the user reference, does it make sense in RDM?
Not really, but the autogenerated request should have the record owner as its creator.

> * [ ]  The ETL classes should be minimal:
>   * [ ]  Two attributes, community and record id, destination table `rdm_parents_community`
I think, `record_id` is the parent record ID, which should be taken from the cache.

>   * [ ]  If the IR expired add Accepted Action otherwise a Expired Action. Zenodo does not keep track of Declined/Cancel actions. Create the Request Event of the corresponding type in [request_events](https://github.com/inveniosoftware/invenio-requests/blob/master/invenio_requests/records/models.py#L38). Can follow the types in the [submission review request](https://github.com/inveniosoftware/invenio-rdm-records/blob/master/invenio_rdm_records/requests/community_submission.py#L127).
No need for this, since we're not expiring requests on Zenodo at all :)

> **Extra**
> 
> * [ ]  Should the M2M mixin be moved to rdm-records since it has context (requires) a record class to work? alternatively, move it to the `communities/records/` since it makes no sense to have an external `records/` in this module.
Somewhat agree, since:

- the `invenio_communities/records/` folder doesn't actually contain much
- all the mixins/systemfields are only becoming relevant and used in `rdm-records`
- I don't see any future usage where we connect some other model to communities

> * [ ]  Take into account [investigation: db table per request type inveniosoftware/invenio-requests#303](https://github.com/inveniosoftware/invenio-requests/issues/303)
Currently in Zenodo production, we have 3.8M rows in the `communities_community_record` table, which would translate to the same number of rows in the requests table. Another factor to take into account is the number of events (comments + actions).

**Comment by ppanero** [comment]
From Discord (https://discord.com/channels/692989811736182844/1065305118121144510/1080048010626605187)

Since we do not need to migrate `zenodo` (and potentially `ecfunded` neither) we can filter those when creating the dump. The result would be:

- without zenodo it's 617,648
- if we also take out ecfunded: 200,960

**Comment by ppanero** [comment]
Using joins the resulting query the following, and it runs quite fast.

```sql
SELECT pidstore_pid.pid_value as parent_recid, communities_community_record.created, communities_community_record.updated, communities_community_record.id_community FROM pidstore_pid INNER JOIN (
    pidrelations_pidrelation INNER JOIN (
        pidstore_pid as inner_store INNER JOIN communities_community_record ON inner_store.object_uuid=id_record AND id_community!='zenodo' AND id_community!='ecfunded'
    ) ON child_id=inner_store.id
) ON pidstore_pid.id=parent_id limit 1;
```

However, I can see a difference in the count between:

```sql

zenodo=>  SELECT count(pidstore_pid.pid_value) FROM pidstore_pid INNER JOIN (
    pidrelations_pidrelation INNER JOIN (
        pidstore_pid as inner_store INNER JOIN communities_community_record ON inner_store.object_uuid=id_record AND id_community!='zenodo' AND id_community!='ecfunded'
    ) ON child_id=inner_store.id
) ON pidstore_pid.id=parent_id limit 1;

 count
-------
 61814
(1 row)

zenodo=> SELECT count(*) FROM communities_community_record WHERE id_community!='zenodo' and id_community!='ecfunded';
 count
-------
 64957
(1 row)
```

Could it be due to records that do not have versioning? (e.g. external DOIs?) Goint to test the JSON option.

**Comment by ppanero** [comment]
Using a distinct the one off persists. The different number makes sense since there can be multiple tuples with same parent id but different community id. However, the one off should have dissapeared.

```sql
zenodo=> SELECT count(distinct(r.json->'conceptrecid')) FROM records_metadata AS r INNER JOIN communities_community_record AS cr ON cr.id_record = r.id AND id_community!='zenodo' AND id_community!='ecfunded' AND r.json->'conceptrecid' IS NOT NULL;
 count
-------
 61596
(1 row)

zenodo=> SELECT count(distinct(pidstore_pid.pid_value)) FROM pidstore_pid INNER JOIN (
    pidrelations_pidrelation INNER JOIN (
        pidstore_pid as inner_store INNER JOIN communities_community_record ON inner_store.object_uuid=id_record AND id_community!='zenodo' AND id_community!='ecfunded'
    ) ON child_id=inner_store.id
) ON pidstore_pid.id=parent_id;
 count
-------
 61595
(1 row)
```

**Comment by ppanero** [comment]
The one of comes from pid `257417`

```sql
zenodo=> (SELECT (r.json->>'conceptrecid')::character varying FROM records_metadata AS r INNER JOIN communities_community_record AS cr ON cr.id_record = r.id AND id_community!='zenodo' AND id_community!='ecfunded' AND r.json->'conceptrecid' IS NOT NULL) EXCEPT (SELECT pidstore_pid.pid_value as conceptrecid FROM pidstore_pid INNER JOIN (
    pidrelations_pidrelation INNER JOIN (
        pidstore_pid as inner_store INNER JOIN communities_community_record ON inner_store.object_uuid=id_record AND id_community!='zenodo' AND id_community!='ecfunded'
    ) ON child_id=inner_store.id
) ON pidstore_pid.id=parent_id);
 varchar
---------
 257417
(1 row)
```

**Comment by ppanero** [comment]
After adding the pid status check, using the JSON blob becomes a bit more complex, however it returns the same count

```sql
zenodo=> SELECT count(pid_value) FROM pidstore_pid INNER JOIN (
    SELECT (r.json->>'conceptrecid')::character varying as conceptrecid FROM records_metadata AS r INNER JOIN
        communities_community_record AS cr
    ON cr.id_record = r.id AND id_community!='zenodo' AND id_community!='ecfunded'
) as concepts ON pid_value=concepts.conceptrecid AND pidstore_pid.status='M';
 count
-------
 61815
 ```

**Comment by ppanero** [comment]
The `_id_user` is always `NULL` therefore if we want to exclude deactivate users we need to use the json blob approach. We need to consider if we might need to reactivate after migration (data won't be present).

```sql
zenodo=> SELECT count(accounts_user.id) FROM accounts_user INNER JOIN (
    SELECT (r.json#>>'{owners, 0}')::integer AS owners FROM records_metadata AS r INNER JOIN
        communities_community_record AS cr
    ON cr.id_record = r.id AND id_community!='zenodo' AND id_community!='ecfunded'
) as records ON accounts_user.id=records.owners AND NOT accounts_user.active;

 count
-------
    28
(1 row)
```
