### ISSUE TITLE
Migration: records

### ISSUE THREAD

**Issue by kpsherva** [zenodo/zenodo-rdm#244]
```[tasklist]
### Tasks
- [x] https://github.com/zenodo/zenodo-rdm/issues/241
- [ ] https://github.com/zenodo/zenodo-rdm/issues/305
- [ ] https://github.com/zenodo/zenodo-rdm/issues/242
```
