### ISSUE TITLE
Migration: files investigation

### ISSUE THREAD

**Issue by kpsherva** [zenodo/zenodo-rdm#251]
see https://github.com/zenodo/rdm-project/issues/112

## Report

For the files migration we are interested in the following 3 tables:
- records_metadata
- files_bucket
- records_buckets

The reason for the above is that we want to ensure that all records that are intended to have a bucket i.e published records and drafts, are included in `records_buckets` table and vice verca i.e all record buckets are belonging to `records_metadata` drafts and published. Moreover, we need to ensure that all buckets in the `record_buckets` table are included in the `files_bucket` one and vice versa all files buckets are existing in the `record_buckets` table.

## Necessary condition

- All published records and drafts are part of the `records_buckets` table
- All buckets from `records_buckets` table are part of the `files_bucket` table

## Cleanup/Investigate condition

- All records that are drafts and published and are not part of `records_buckets` table
- All file buckets that are not part of `records_buckets` table

### Count of all records_metadata

```sql
SELECT COUNT(DISTINCT(id)) FROM records_metadata;
```

| count   |
| ------- |
| 10881411 |

### Count of all records_buckets

```sql
SELECT COUNT(DISTINCT(record_id)) FROM records_buckets;
```

| count   |
| ------- |
| 6486994 |

### Crosscheck of records_metadata and records_buckets

From the results above we have a difference between of the 2 tables:

| records_metadata | records_buckets | difference  |
| ---------------- | --------------- | ----------- |
| 10881345         | 7414346         | **3466999** |

Following we run some reasoning on the `records_metadata` table so we can explain that difference.

#### Query records without bucket, grouped by schema field

```sql
WITH missing AS ((
    SELECT id FROM records_metadata AS r
) EXCEPT (
    SELECT record_id AS id from records_buckets
))
SELECT (r.json->>'$schema')::character varying AS schema, COUNT(*) FROM records_metadata AS r
JOIN missing ON r.id = missing.id GROUP BY schema;
```

| schema                                                         | count   |
| -------------------------------------------------------------- | ------- |
| https://zenodo.org/schemas/deposits/records/record-v1.0.0.json | 6       |
| https://zenodo.org/schemas/records/record-v1.0.0.json          | 18      |
| http://zenodo.org/schemas/funders/funder-v1.0.0.json           | 21496   |
| http://zenodo.org/schemas/grants/grant-v1.0.0.json             | 3494892 |
| http://zenodo.org/schemas/licenses/license-v1.0.0.json         | 531     |
|                                                                | 877473  |

**ACTION**: Check the `18+6=24` records with `$schema` equals to `deposits/records/record-v1.0.0.json` or `records/records/record-v1.0.0.json`

Let's further investigate the null schema missing records.

#### Query records with missing bucket, where schema is NULL, grouped by pid type

```sql
WITH missing AS ((
    SELECT id FROM records_metadata AS r
) EXCEPT (
    SELECT record_id AS id from records_buckets
)), ids AS (
SELECT r.id FROM records_metadata AS r
    JOIN missing ON r.id = missing.id WHERE (r.json->>'$schema')::character varying IS NULL
) SELECT pid_type, COUNT(*) FROM ids JOIN pidstore_pid ON ids.id = pidstore_pid.object_uuid GROUP BY pid_type; 
```

| pid_type | count  |
| -------- | ------ |
| depid    | 478958 |
| doi      | 688880 |
| eurepo   | 203    |
| grant    | 203    |
| oaf      | 203    |
| oai      | 391913 |
| recid    | 398259 |

However if we check the status we can see that most of them belong to deleted records:

```sql
WITH missing AS ((
    SELECT id FROM records_metadata AS r
) EXCEPT (
    SELECT record_id AS id from records_buckets
)), ids AS (
SELECT r.id FROM records_metadata AS r
    JOIN missing ON r.id = missing.id WHERE (r.json->>'$schema')::character varying IS NULL
) SELECT status, COUNT(*) FROM ids JOIN pidstore_pid ON ids.id = pidstore_pid.object_uuid WHERE pid_type='recid' OR pid_type='depid' GROUP BY status;
```

| status | count  |
| ------ | ------ |
| D      | 876895 |

**ACTION** There is a difference of 322 between the count of deleted records/deposits without bucket and the list of grouped by pid type above (876895 - 398259 - 478958 = - 322). Tried with a `DISTINCT` but it is not the reason.

#### Records (not funders, nor grants, nor license) without a bucket, that are active (i.e. pid not deleted)

We can filter by pid type since grants are `grant`, funders are `frdoi` (funder DOI), and licenses are `odlic` (open definition license).

```sql
WITH missing AS ((
     SELECT id FROM records_metadata AS r
 ) EXCEPT (
     SELECT record_id AS id from records_buckets
 )), recids AS (
 SELECT r.id FROM records_metadata AS r
     JOIN missing ON r.id = missing.id
)

SELECT COUNT(*) FROM recids JOIN pidstore_pid ON recids.id = pidstore_pid.object_uuid
     WHERE (pid_type='recid' OR pid_type='depid') AND status != 'D';

 count
-------
     5
(1 row) 
```

The following query gives the 5 pids, records that need to be checked

```sql
WITH missing AS ((
     SELECT id FROM records_metadata AS r
 ) EXCEPT (
     SELECT record_id AS id from records_buckets
 )), recids AS (
 SELECT r.id FROM records_metadata AS r
     JOIN missing ON r.id = missing.id
) SELECT pid_value, object_uuid FROM recids JOIN pidstore_pid ON recids.id = pidstore_pid.object_uuid
     WHERE (pid_type='recid' OR pid_type='depid') AND status != 'D';

#### Query how many file buckets are not connected with any record

### Count of all files_buckets

```sql
SELECT COUNT(DISTINCT(id)) FROM files_bucket;
```

| count   |
| ------- |
| 7212820 |

```sql
SELECT COUNT(DISTINCT(bucket_id)) FROM records_bucket;
```

| count   |
| ------- |
| 6950735 |

```sql
WITH missing_file_buckets AS ((
  SELECT DISTINCT(id) FROM files_bucket
) EXCEPT (
  SELECT DISTINCT(bucket_id) AS id from records_buckets
))
SELECT COUNT(*) FROM missing_file_buckets;
```

| count  |
| ------ |
| 262091 |

**ACTION**: These are orphan buckets, what do we do with them?

### Objects without a bucket and viceversa

_All file objects belong to a bucket, but not all buckets contain file objects_

```sql
WITH missing_file_objects AS ((
  SELECT DISTINCT(bucket_id) AS id from files_object
) EXCEPT (
  SELECT DISTINCT(id) FROM files_bucket
))
SELECT COUNT(*) FROM missing_file_objects;
```

| count |
| ----- |
| 0     |
(1 row)

```sql
WITH missing_buckets AS ((
  SELECT DISTINCT(id) FROM files_bucket
) EXCEPT (
  SELECT DISTINCT(bucket_id) AS id from files_object
))
SELECT COUNT(*) FROM missing_buckets;
```

| count  |
| ------ |
| 341714 |

Most of the buckets without files belong to deposits, therefore we can consider that they are "not uploaded yet".

**ACTION** Investigate the 4 DOIs and 5 recid without file objects.

```sql
WITH missing_buckets AS (
    (
      SELECT DISTINCT(id) FROM files_bucket
    ) EXCEPT (
      SELECT DISTINCT(bucket_id) AS id from files_object
    )
), record_ids AS (
    SELECT record_id FROM missing_buckets JOIN records_buckets
        ON missing_buckets.id=records_buckets.bucket_id
)

SELECT pid_type, COUNT(*) FROM pidstore_pid JOIN record_ids
    ON pidstore_pid.object_uuid=record_ids.record_id
    GROUP BY pidstore_pid.pid_type;
```

| pid_type | count |
| -------- | ----- |
| depid    | 79812 |
| doi      | 5     |
| oai      | 4     |
| recid    | 4     |

### Objects without actual files and viceversa

```sql
SELECT count(DISTINCT(id)) FROM files_files;
```
| count    |
| -------- |
| 11322490 |

```sql
SELECT count(DISTINCT(file_id)) AS id from files_object
```

| id      |
| ------- |
| 9550386 |

```sql
WITH empty_file_objects AS ((
  SELECT DISTINCT(file_id) AS id from files_object
) EXCEPT (
  SELECT DISTINCT(id) FROM files_files
))
SELECT COUNT(*) FROM empty_file_objects;
```

| count |
| ----- |
| 1     |

**ACTION**: It is a file object with empty id, check which it does not not have files and if it can be excluded from migration. The query without count returned:

```
SELECT id FROM empty_file_objects;
 id
----

(1 row)
```

```sql
WITH orphan_files AS ((
  SELECT DISTINCT(id) FROM files_files
) EXCEPT (
  SELECT DISTINCT(file_id) AS id from files_object
))
SELECT COUNT(*) FROM orphan_files;
```

| count   |
| ------- |
| 1772117 |

**ACTION** What do we do with these ones? We cannot trace it back to records since they are not linked to file objects.

## Extract query

```sql
COPY (
    SELECT row_to_json(files)
    FROM (
        WITH active_fb AS (
            SELECT 
                created AS fb_created,
                updated AS fb_updated,
                id AS fb_id,
                default_location AS fb_default_location,
                default_storage_class AS fb_default_storage_class,
                size AS fb_size,
                quota_size AS fb_quota_size,
                max_file_size AS fb_max_file_size,
                locked AS fb_locked,
                deleted AS fb_deleted
            FROM records_buckets AS rb 
                INNER JOIN files_bucket AS fb ON rb.bucket_id=fb.id
        ), active_fo AS (
            SELECT 
                active_fb.*,
                created AS fo_created,
                updated AS fo_updated,
                bucket_id AS fo_bucket_id,
                key AS fo_key,
                version_id AS fo_version_id,
                file_id AS fo_file_id,
                _mimetype AS fo_mimetype,
                is_head AS fo_is_head
            FROM active_fb 
                INNER JOIN files_object ON active_fb.rb_bucket_id=files_object.bucket_id
        )

        SELECT
            active_fo.*,
            created AS ff_created,
            updated AS ff_updated,
            id AS ff_id,
            uri AS ff_uri,
            storage_class AS ff_storage_class,
            size AS ff_size,
            checksum AS ff_checksum,
            readable AS ff_readable,
            writable AS ff_writable,
            last_check_at AS ff_last_check_at,
            last_check AS ff_last_check
        FROM active_fo 
                INNER JOIN files_files ON active_fo.fo_file_id=files_files.id
    ) as files
    LIMIT 5
) TO STDOUT;
```
 ## Next steps

```[tasklist]
### Tasks
- [x] Investigate the `**ACTIONS**` points and cleanup/update the report once an alignment has been reached.
- [x] Prove that all `record._files` are synced with the records_buckets information, BUSTED
- [x] Record Files implementation integration. Can be done in parallel so we achieve the goal of full zenodo dump assumning that
                  - All record buckets are the one and only that need to be migrated along with the records
                  - All records to be migrated, include valid/synced files information i.e `record._files` and equal to the linked buckets.
- [ ] Draft files implementation.
- [ ] Communities files implementation.
```
