### ISSUE TITLE
Migration: communities

### ISSUE THREAD

**Issue by slint** [zenodo/zenodo-rdm#303]
### Tasks
- [ ] https://github.com/zenodo/zenodo-rdm/issues/258
- [ ] https://github.com/zenodo/zenodo-rdm/issues/229
- [ ] https://github.com/zenodo/zenodo-rdm/issues/312
