### ISSUE TITLE
Migration: records metadata

### ISSUE THREAD

**Issue by slint** [zenodo/zenodo-rdm#307]
### Tasks
- [ ] https://github.com/zenodo/zenodo-rdm/issues/308
- [ ] https://github.com/zenodo/zenodo-rdm/issues/262
- [ ] https://github.com/zenodo/zenodo-rdm/issues/245
- [ ] https://github.com/zenodo/zenodo-rdm/issues/313
- [ ] https://github.com/zenodo/zenodo-rdm/issues/301
- [ ] https://github.com/zenodo/zenodo-rdm/issues/314
- [ ] https://github.com/zenodo/zenodo-rdm/issues/323
- [ ] https://github.com/zenodo/zenodo-rdm/issues/479
