### ISSUE TITLE
Migration: files

### ISSUE THREAD

**Issue by slint** [zenodo/zenodo-rdm#309]
```[tasklist]
### Tasks
- [x] https://github.com/zenodo/zenodo-rdm/issues/251
- [x] migration: raw tables import from legacy to RDM
- [ ] https://github.com/zenodo/zenodo-rdm/issues/310
- [ ] https://github.com/zenodo/zenodo-rdm/issues/311
- [ ] https://github.com/zenodo/zenodo-rdm/issues/312
- [ ] https://github.com/zenodo/zenodo-rdm/issues/422
```
