### ISSUE TITLE
communities: omit setting default community when multiple found in legacy

### ISSUE THREAD

**Issue by zzacharo** [zenodo/zenodo-rdm#373]
# Migration
At the moment, we set always the default community to the first we find, when we migrate records from Zenodo legacy. We should

- [x] Set the default only if the record belongs to one community
- [x] Leave empty otherwise

# UI Blockers/Needs investigation

- [x] We need to investigate if the UI is not broken when a community is in the `parent.communities.ids` but not in the `parent.communities.default`. For example, the deposit form should still identify the record as part of a community.
- [ ] We miss the functionality to actively set a community as a default or "brand" community.
  - [ ] Who can set this? Record owner?

**Comment by slint** [comment]
Implemented as described. For setting the default branding see https://github.com/zenodo/rdm-project/issues/188
