### ISSUE TITLE
migration: change data capture actions ETL

### ISSUE THREAD

**Issue by slint** [zenodo/zenodo-rdm#427]
For each of the available actions in legacy Zenodo, we need to:

1. implement the equivalent/target `LoadAction` action in `invenio-rdm-migrator`
2. produce a sample of the action's DB transaction from the legacy system
3. implement the `TransformLoad` that uniquely detects/fingerprints the above transaction and transforms it to the target `LoadAction`'s data model

```[tasklist]
### Tasks
- [ ] https://github.com/zenodo/zenodo-rdm/issues/428
- [ ] https://github.com/zenodo/zenodo-rdm/issues/429
- [ ] https://github.com/zenodo/zenodo-rdm/issues/430
- [ ] https://github.com/zenodo/zenodo-rdm/issues/424
- [ ] https://github.com/zenodo/zenodo-rdm/issues/432
- [ ] https://github.com/zenodo/zenodo-rdm/issues/433
- [ ] https://github.com/zenodo/zenodo-rdm/issues/434
- [ ] https://github.com/zenodo/zenodo-rdm/issues/437
- [ ] https://github.com/zenodo/zenodo-rdm/issues/435
- [ ] https://github.com/zenodo/zenodo-rdm/issues/436
```
