### ISSUE TITLE
Community Frontpage

### ISSUE THREAD

**Issue by carlinmack** [zenodo/zenodo-rdm#685]
RFC: https://codimd.web.cern.ch/E-79NQAyST-bmxXLH07vVQ?both

Branch: https://github.com/inveniosoftware/invenio-communities/tree/feature/ec-frontpage

```[tasklist]
### Tasks
- [ ] https://github.com/zenodo/zenodo-rdm/issues/688
- [ ] https://github.com/zenodo/zenodo-rdm/issues/689
- [ ] https://github.com/zenodo/zenodo-rdm/issues/690
- [ ] https://github.com/zenodo/zenodo-rdm/issues/691
- [ ] https://github.com/zenodo/zenodo-rdm/issues/692
- [ ] https://github.com/zenodo/zenodo-rdm/issues/706
```

```[tasklist]
### 1st iteration Feedback list
- [ ] https://github.com/zenodo/zenodo-rdm/issues/715
- [x] link to go to the community in the header (Anika)
- [x] deposit form: bring back the "new upload" button (Anika)
- [x] New upload button should not open a new window (Anika)
- [x] select community modal: community upload form -> remove the blue change "Go to the community" pointing to frontpage (Anika)
- [x] recent uploads heading missing (Anika)
- [x] make sure we use the same icon for verified, remove the question mark, could be with a tooltip instead (Anika)
- [x] remove "no description" (Anika)
- [x] Remove links "FAIR publishing", "Integrations" from footer, in the "About" section remove everything and put "Learn more" (Anika)
- [x] use checkmark for the "verified" logo(icon
- [x] center "verified" community in the site_footer, remove "learn more"
- [x] menu order broken
- [x] frontpage: label colouring should follow the EC theme
- [x] powered by InvenioRDM -> powered by CERN Data Center (current zenodo one)
- [ ] https://github.com/zenodo/zenodo-rdm/issues/716
- [ ] https://github.com/zenodo/zenodo-rdm/issues/717
```

Notes: Not react based due to loading time

![image](https://github.com/zenodo/zenodo-rdm/assets/6676843/856ed5cb-1b69-4e50-9f59-0e1d9f7fc125)

### Questions

* Do we apply spilt form workflow for all the communities or just the branded ones? Do we remove the community selection component from general form entirely ?
* Where does the Learn More button go?
* Is there a view of all the subcommunities? (a tab? menu?)
* Is the support form our scope?
  * Is the support form prefilled to join waiting list or is it an email?
* Do we allow anyone to use any theme? Seems like we have some duty to "protect" the EC's brand for ex

- Request pages
- My uploads - clearly indicate if an upload goes to EC (i.e. show community).
- Link for specific community upload
