### ISSUE TITLE
List all changes for all pages (community styling)

### ISSUE THREAD

**Issue by kpsherva** [zenodo/zenodo-rdm#688]
# TODO
- [x] Community search `communities/ec`
- [x] Community requests `/communities/ec/requests`
- [x] Request details page (when reaching from community page) `/communities/ec/requests/1f3d5feb-1f9b-43d4-ba3a-f1270cca9a9b`
- [x] Community members `/communities/ec/members`
- [x] Community invitations `/communities/ec/invitations`
- [x] Community invitation details (when arriving from community page) `communities/ec/requests/3ef83fd5-adbf-48c1-b84f-39c38607d3dc`
- [x] upload form
- [x] gray out community if marked as verified on the search of the generic upload form

![Image](https://github.com/zenodo/zenodo-rdm/assets/38131488/5a493801-20fe-42de-aedf-0252c9eb3bb7)

~~my dashboard: Uploads to verified community to be highlighted in search -> try some mockups~~ moved to another issue
~~generic search: Uploads to verified community to be highlighted in search -> try some mockups~~ moved to another issue
~~record landing page: add "verified" badge to the list of communities -> try some mockups~~ moved to another issue

# Should be done? 

- community invitation (when arriving from "my dashboard") -> not for now, to be tested
- community inclusion request (when arriving from "my dashboard") - probably it shouldn't be done, since the visual identity should not be added before accepting the record as a part of the community ->  not for now, to be tested
- featured communities: add "verified" badge? -> yes, to be decided how exactly

# Questions:

- [ ] Should we harmonize all the community headers to one style? -> not at this point
- [ ] Do we have the grayed out zenodo header for any community that is themed? meaning that is has either colors specified/custom templating applied or both) -> not at this point
- [ ] Should the community frontpage text (hero section) be editable for the user? -> not for now, until we know what more variables are needed
