### ISSUE TITLE
Sub-communities indexing

### ISSUE THREAD

**Issue by slint** [zenodo/zenodo-rdm#694]
```[tasklist]
### Tasks
- [ ] https://github.com/zenodo/zenodo-rdm/issues/696
- [ ] https://github.com/zenodo/zenodo-rdm/issues/697
- [ ] https://github.com/zenodo/zenodo-rdm/issues/699
- [ ] https://github.com/zenodo/zenodo-rdm/issues/698
- [ ] https://github.com/zenodo/zenodo-rdm/issues/700
- [ ] https://github.com/zenodo/zenodo-rdm/issues/701
- [ ] https://github.com/zenodo/zenodo-rdm/issues/702
```
