### ISSUE TITLE
Setup IIP server

### ISSUE THREAD

**Issue by slint** [zenodo/zenodo-rdm#815]
```[tasklist]
### Tasks
- [ ] https://github.com/zenodo/zenodo-rdm/issues/823
- [ ] https://github.com/zenodo/zenodo-rdm/issues/826
- [ ] Detach serving of IIIF Image and Presentation layers
- [ ] Split routing of `/api/iiif/...` requests
- [ ] Look into authentication
- [ ] https://github.com/inveniosoftware/invenio-rdm-records/issues/1728
```

**Comment by alejandromumo** [comment]
Note to self: In the InvenioRDM contex keep in mind configurability, what can be enabled / disabled, what has to be there for this to work, etc.
