### ISSUE TITLE
Image tile generation

### ISSUE THREAD

**Issue by slint** [zenodo/zenodo-rdm#816]
```[tasklist]
### Tasks
- [ ] https://github.com/zenodo/zenodo-rdm/issues/821
- [ ] https://github.com/zenodo/zenodo-rdm/issues/825
- [ ] https://github.com/zenodo/zenodo-rdm/issues/828
- [ ] https://github.com/zenodo/zenodo-rdm/issues/822
- [ ] https://github.com/zenodo/zenodo-rdm/issues/820
```
