### ISSUE TITLE
Implement tif generation state management

### ISSUE THREAD

**Issue by yashlamba** [zenodo/zenodo-rdm#841]
```[tasklist]
### Tasks
- [ ] https://github.com/zenodo/zenodo-rdm/issues/842
- [ ] Implement component to create state management media file
- [ ] https://github.com/zenodo/zenodo-rdm/issues/843
```

**Comment by yashlamba** [comment]
Closed via: https://github.com/inveniosoftware/invenio-rdm-records/pull/1735
