### ISSUE TITLE
Horizon-ZEN Release 2

### ISSUE THREAD

**Issue by alejandromumo** [zenodo/zenodo-rdm#861]
https://zenodo.org/records/8199881

### Tasks
- [ ] https://github.com/zenodo/zenodo-rdm/issues/864
- [ ] https://github.com/zenodo/zenodo-rdm/issues/866
- [ ] https://github.com/inveniosoftware/invenio-communities/issues/1147
- [ ] https://github.com/zenodo/zenodo-rdm/issues/890
- [ ] https://github.com/zenodo/zenodo-rdm/issues/891
- [x] https://github.com/zenodo/zenodo-rdm/issues/888
- [ ] https://github.com/zenodo/zenodo-rdm/issues/897
- [ ] https://github.com/zenodo/ops/issues/469
