### ISSUE TITLE
Design the feature, write in RFC

### ISSUE THREAD

**Issue by carlinmack** [zenodo/zenodo-rdm#864]
[RFC](https://codimd.web.cern.ch/Xg046pEjTLaY1ySyUPAEug#)
```[tasklist]
### Tasks
- [ ] https://github.com/zenodo/zenodo-rdm/issues/869
- [ ] https://github.com/zenodo/zenodo-rdm/issues/865
- [ ] https://github.com/zenodo/zenodo-rdm/issues/866
```

**Comment by carlinmack** [comment]
## Nice to have

```[tasklist]
### Tasks
- [ ] 
```
