### ISSUE TITLE
Subcommunities Milestone 1 fixes

### ISSUE THREAD

**Issue by carlinmack** [zenodo/zenodo-rdm#866]
```[tasklist]
### Tasks
- [ ] https://github.com/zenodo/zenodo-rdm/issues/884
- [ ] https://github.com/zenodo/zenodo-rdm/issues/885
- [ ] https://github.com/zenodo/zenodo-rdm/issues/882
- [ ] https://github.com/zenodo/zenodo-rdm/issues/886
- [ ] https://github.com/zenodo/zenodo-rdm/issues/881
- [ ] https://github.com/zenodo/zenodo-rdm/issues/889
- [ ] https://github.com/zenodo/zenodo-rdm/issues/883
```
