### ISSUE TITLE
Subcommunities Milestone 2 fixes

### ISSUE THREAD

**Issue by alejandromumo** [zenodo/zenodo-rdm#899]
### Tasks
- [ ] https://github.com/zenodo/zenodo-rdm/issues/909
- [ ] https://github.com/zenodo/zenodo-rdm/issues/910
- [ ] https://github.com/zenodo/zenodo-rdm/issues/906
- [ ] https://github.com/zenodo/zenodo-rdm/issues/898
- [ ] Make 'visibility' settings part of the payload and process it in the backend
- [ ] https://github.com/zenodo/zenodo-rdm/issues/901
- [ ] https://github.com/zenodo/zenodo-rdm/issues/902
- [ ] New community request shows up as "deleted"
- [ ] https://github.com/zenodo/zenodo-rdm/issues/903
- [ ] https://github.com/zenodo/zenodo-rdm/issues/904
- [ ] https://github.com/zenodo/zenodo-rdm/issues/905
- [ ] https://github.com/zenodo/zenodo-rdm/issues/908
- [ ] https://github.com/zenodo/zenodo-rdm/issues/900
