### ISSUE TITLE
FAIRCORE4EOSC - production launch

### ISSUE THREAD

**Issue by alejandromumo** [zenodo/zenodo-rdm#927]
```[tasklist]
### Tasks
- [ ] https://github.com/inveniosoftware/invenio-swh/issues/33
- [ ] https://github.com/zenodo/zenodo-rdm/issues/929
- [ ] https://github.com/zenodo/zenodo-rdm/issues/936
- [ ] https://github.com/inveniosoftware/invenio-swh/issues/23
- [ ] https://github.com/zenodo/zenodo-rdm/issues/928
- [ ] iframe: show embedded iframe from SWH (we might need to pass the first directory PATH
- [ ] https://github.com/zenodo/zenodo-rdm/issues/937
```

**Comment by alejandromumo** [comment]
We are waiting for Software Heritage team to give us deposit permissions in their system, afterwards we can flip the switch in production for this. 

It is missing the export of the SWH field, but it will take some time to figure it out. 

That said, I am closing this EPIC and moving the leftover task out of it.
