### ISSUE TITLE
Horizon-ZEN Milestone 1

### ISSUE THREAD

**Issue by alejandromumo** [zenodo/zenodo-rdm#977]
```[tasklist]
### Tasks
- [ ] https://github.com/zenodo/zenodo-rdm/issues/978
- [ ] https://github.com/zenodo/zenodo-rdm/issues/979
- [ ] https://github.com/zenodo/zenodo-rdm/issues/985
- [x] Browse page deployment
- [ ] https://github.com/zenodo/zenodo-rdm/issues/986
- [x] "New" EuroSciVoc vocabulary deployment
- [ ] https://github.com/zenodo/zenodo-rdm/issues/990
- [ ] https://github.com/inveniosoftware/invenio-vocabularies/issues/381
```
